<?php

/**
 * BrandTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BrandTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BrandTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Brand');
    }
}