<?php

/**
 * HavelistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HavelistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HavelistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Havelist');
    }
    public static function updateObject($id,$objectId)
    {
    	$q= Doctrine_Core::getTable('HaveList')->
    				      createQuery()->
    				      update()->
    				      set('object_id',$objectId)->
    				      where('id = ?',$id);	
        return $q->execute();
    }
	public static function getProductsToSwapFor($productId)
	{
		$q = Doctrine_Core::getTable('Havelist')
		->createQuery('u')
		->select('Havelist.*')
		->from('Havelist,Product,Wantlist,sfGuardUser')
		->where('Wantlist.product_id = ?',$productId)
		->andWhere('sfGuardUser.id = Wantlist.user_id')
		->andWhere('Havelist.user_id = sfGuardUser.id')
		->addGroupBy('Havelist.product_id');
		
		return $q->execute();
	}
}