<?php

/**
 * HavelistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HavelistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HavelistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Havelist');
    }
    public static function updateObject($id,$objectId)
    {
    	$q= Doctrine_Core::getTable('HaveList')->
    				      createQuery()->
    				      update()->
    				      set('object_id',$objectId)->
    				      where('id = ?',$id);	
        return $q->execute();
    }
}