<?php

/**
 * HavelistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HavelistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HavelistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Havelist');
    }
}