<?php

/**
 * ProductTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object ProductTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Product');
	}
<<<<<<< HEAD

	public static function getLuceneIndex()
=======
	/*
	public function getLuceneIndex()
>>>>>>> 655749c0619eb87c63b60b984a8f5780bf2fa9f2
	{
	  ProjectConfiguration::registerZend();

	  if (file_exists($index = ProductTable::getLuceneIndexFile()))
	  {
	    return Zend_Search_Lucene::open($index);
	  }
	  else
	  {
	    return Zend_Search_Lucene::create($index);
	  }
	}

public function getForLuceneQuery($query)
{
  $hits = self::getLuceneIndex()->find($query);
 
  $pks = array();
  foreach ($hits as $hit)
  {
    $pks[] = $hit->pk;
  }
 
  if (empty($pks))
  {
    return array();
  }
 
  $q = $this->createQuery('j')
    ->whereIn('j.id', $pks)
    ->limit(20);
 
  return $q->execute();
}

	public static function getLuceneIndexFile()
	{
	  return sfConfig::get('sf_data_dir').'\products.'.sfConfig::get('sf_environment').'.index';
	}*/
}