<?php

/**
 * ProductTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object ProductTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Product');
	}

	public static function getLuceneIndex()

	{
	  ProjectConfiguration::registerZend();

	  if (file_exists($index = ProductTable::getLuceneIndexFile()))
	  {
	    return Zend_Search_Lucene::open($index);
	  }
	  else
	  {
	    return Zend_Search_Lucene::create($index);
	  }
	}

	public function getForLuceneQuery($query, $category)
	{
  		$hits = self::getLuceneIndex()->find($query);
 
	  	$pks = array();
  		foreach ($hits as $hit)
    		$pks[] = $hit->pk;
 
  		if (empty($pks))
  		  return array();
 
  		$q = $this->createQuery('producto')
   	 	->whereIn('producto.id', $pks)
      ->andWhere('producto.id_category = ?', $category)
   	 	->limit(20);
	  	return $q->execute();
	}

	public static function getLuceneIndexFile()
	{
	  	return sfConfig::get('sf_data_dir').'/products.'.sfConfig::get('sf_environment').'.index';
	}
}
