<?php

/**
 * RateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rate');
    }
}