<?php

/**
 * TradeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TradeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TradeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Trade');
    }
}