<?php

/**
 * Trade
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    trocar
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Trade extends BaseTrade
{
	public static function ComposeMail($to,$html){
		
		$message = sfContext::getInstance()->getMailer()->compose();
		$subject = "Trocar: Aviso de Intercambio";
		$from    = "admin@trocar.cl";

		$message->setSubject($subject);
		$message->setTo($to);
		$message->setFrom($from);
		$message->setBody($html,"text/html");
		return $message;
	}
}
