<?php

/**
 * WantlistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WantlistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WantlistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Wantlist');
    }
}