# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }
  
facebook_connect:
  url:   /facebook_connect
  param: {  module: user, action: fbConnect }

register:
  url:   /register
  param: { module: user, action: register }
  
sf_guard_signin:
  url: /login 
  params: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url: /logout
  params: { module: sfGuardAuth, action: signout }

oferto_index: 
  url: /oferto
  params: { module: have_list, action: index }

oferto:
  url: /oferto/:action/*
  params: { module: have_list }
  
busco_index:
  url: /busco
  params: { module: wantlist, action: index }
 
busco:
  url: /busco/:action/*
  params: { module: wantlist }
  
intercambio_index:
  url: /intercambio
  params: { module: trade, action: index }
  
intercambio:
  url: /intercambio/:action/*
  params: { module: trade }
   
products_search:
  url:   /search2.:sf_format
  param: { module: products, action: search, sf_format: html }
  requirements:
    sf_format: (?:html|js)

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
