<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('havelist', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'id_product' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'id_object' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('object', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'status' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'detail' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'picture' => 
             array(
              'type' => 'string',
              'length' => '200',
             ),
             'weight' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'height' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'width' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'lenght' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'is_new' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'color' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('product', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'picture' => 
             array(
              'type' => 'string',
              'length' => '200',
             ),
             'link' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'brand' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'model' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('havelist');
        $this->dropTable('object');
        $this->dropTable('product');
    }
}