<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('havelist', 'havelist_id_product_product_id', array(
             'name' => 'havelist_id_product_product_id',
             'local' => 'id_product',
             'foreign' => 'id',
             'foreignTable' => 'product',
             ));
        $this->createForeignKey('havelist', 'havelist_id_object_object_id', array(
             'name' => 'havelist_id_object_object_id',
             'local' => 'id_object',
             'foreign' => 'id',
             'foreignTable' => 'object',
             ));
        $this->createForeignKey('havelist', 'havelist_user_id_user_login_id', array(
             'name' => 'havelist_user_id_user_login_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user_login',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('havelist', 'havelist_id_product', array(
             'fields' => 
             array(
              0 => 'id_product',
             ),
             ));
        $this->addIndex('havelist', 'havelist_id_object', array(
             'fields' => 
             array(
              0 => 'id_object',
             ),
             ));
        $this->addIndex('havelist', 'havelist_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('havelist', 'havelist_id_product_product_id');
        $this->dropForeignKey('havelist', 'havelist_id_object_object_id');
        $this->dropForeignKey('havelist', 'havelist_user_id_user_login_id');
        $this->removeIndex('havelist', 'havelist_id_product', array(
             'fields' => 
             array(
              0 => 'id_product',
             ),
             ));
        $this->removeIndex('havelist', 'havelist_id_object', array(
             'fields' => 
             array(
              0 => 'id_object',
             ),
             ));
        $this->removeIndex('havelist', 'havelist_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}