<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('havelist', 'id_object', 'integer', '8', array(
             ));
    }

    public function down()
    {

    }
}