<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('category', 'category_id_root_category_id', array(
             'name' => 'category_id_root_category_id',
             'local' => 'id_root',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->addIndex('category', 'category_id_root', array(
             'fields' => 
             array(
              0 => 'id_root',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('category', 'category_id_root_category_id');
        $this->removeIndex('category', 'category_id_root', array(
             'fields' => 
             array(
              0 => 'id_root',
             ),
             ));
    }
}