<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('havelist', 'havelist_id_product_product_id');
        $this->dropForeignKey('havelist', 'havelist_id_object_object_id');
        $this->dropForeignKey('havelist', 'havelist_user_id_user_login_id');
        $this->createForeignKey('have_list', 'have_list_product_id_product_id', array(
             'name' => 'have_list_product_id_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             ));
        $this->createForeignKey('have_list', 'have_list_object_id_object_id', array(
             'name' => 'have_list_object_id_object_id',
             'local' => 'object_id',
             'foreign' => 'id',
             'foreignTable' => 'object',
             ));
        $this->createForeignKey('have_list', 'have_list_user_id_user_login_id', array(
             'name' => 'have_list_user_id_user_login_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user_login',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('want_list', 'want_list_producto_id_product_id', array(
             'name' => 'want_list_producto_id_product_id',
             'local' => 'producto_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             ));
        $this->createForeignKey('want_list', 'want_list_user_id_user_login_id', array(
             'name' => 'want_list_user_id_user_login_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user_login',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('have_list', 'have_list_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->addIndex('have_list', 'have_list_object_id', array(
             'fields' => 
             array(
              0 => 'object_id',
             ),
             ));
        $this->addIndex('have_list', 'have_list_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('want_list', 'want_list_producto_id', array(
             'fields' => 
             array(
              0 => 'producto_id',
             ),
             ));
        $this->addIndex('want_list', 'want_list_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('havelist', 'havelist_id_product_product_id', array(
             'name' => 'havelist_id_product_product_id',
             'local' => 'id_product',
             'foreign' => 'id',
             'foreignTable' => 'product',
             ));
        $this->createForeignKey('havelist', 'havelist_id_object_object_id', array(
             'name' => 'havelist_id_object_object_id',
             'local' => 'id_object',
             'foreign' => 'id',
             'foreignTable' => 'object',
             ));
        $this->createForeignKey('havelist', 'havelist_user_id_user_login_id', array(
             'name' => 'havelist_user_id_user_login_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user_login',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->dropForeignKey('have_list', 'have_list_product_id_product_id');
        $this->dropForeignKey('have_list', 'have_list_object_id_object_id');
        $this->dropForeignKey('have_list', 'have_list_user_id_user_login_id');
        $this->dropForeignKey('want_list', 'want_list_producto_id_product_id');
        $this->dropForeignKey('want_list', 'want_list_user_id_user_login_id');
        $this->removeIndex('have_list', 'have_list_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->removeIndex('have_list', 'have_list_object_id', array(
             'fields' => 
             array(
              0 => 'object_id',
             ),
             ));
        $this->removeIndex('have_list', 'have_list_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('want_list', 'want_list_producto_id', array(
             'fields' => 
             array(
              0 => 'producto_id',
             ),
             ));
        $this->removeIndex('want_list', 'want_list_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}