<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('want_list', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'producto_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'user_id',
              2 => 'producto_id',
             ),
             ));
        $this->removeColumn('havelist', 'id_product');
        $this->removeColumn('havelist', 'id_object');
        $this->addColumn('have_list', 'product_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('have_list', 'object_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('want_list');
        $this->addColumn('havelist', 'id_product', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('havelist', 'id_object', 'integer', '8', array(
             ));
        $this->removeColumn('have_list', 'product_id');
        $this->removeColumn('have_list', 'object_id');
    }
}