#Lo siguiente es para cambiar el nombre a las tablas que genera el plugin
#sfGuardDoctrine el cual tenia nombres de tablas largos y poco semanticos
#INICIO CAMBIO NOMBRE TABLAS PLUGIN sfDoctrineGuard
sfGuardGroup:
  tableName: groups

sfGuardPermission:
  tableName: permissions

sfGuardGroupPermission:
  tableName: groups_permissions

sfGuardUser:
  tableName:  user_login

sfGuardUserPermission:
  tableName: user_permission

sfGuardUserGroup:
  tableName: user_group

sfGuardRememberKey:
  tableName: remember_key

sfGuardForgotPassword:
  tableName: forgot_password
#FIN CAMBIO NOMBRE TABLAS PLUGIN sfDoctrineGuard

#tabla de perfil de usuario:
sfGuardUserProfile:
  tableName: user_profile
  actAs:
    Timestampable: ~
  columns:
    user_id:        {  type: integer,  notnull: true  }
    first_name:     {  type: string(150)  }
    last_name:      {  type: string(150)  }
    address:        {  type: string(100)  }
    picture:        {  type: string(32)   }
    token:          {  type: string(32)   }
    facebook_uid:   {  type: string(20)   }
  relations:
    User:
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      foreignAlias: Profile
      foreignType:  one
      type:         one
      onDelete:     CASCADE

Havelist:
  tableName: have_list
  actAs:
    Timestampable: ~
  columns:
    id:             {  type: integer,  primary: true,  autoincrement: true, notnull: true  }
    product_id:     {  type: integer,  notnull: true                                       }
    object_id:      {  type: integer                                                       }
    user_id:        {  type: integer,  notnull: true                                       }
  relations:
    Product:
      class:        Product
      local:        product_id
      foreign:      id
      type:         one
    Object:
      class:        Object
      local:        object_id
      foreign:      id
      type:         one
    User:
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      foreignAlias: Havelist
      foreignType:  many
      type:         one
      onDelete:     CASCADE
      
Object:
  tableName: object
  actAs:
    Timestampable: ~
  columns:
    id:        {  type: integer,  primary: true,  autoincrement: true, notnull: true  }
    status:    {  type: string(45)   }
    detail:    {  type: string(255)  }
    picture:   {  type: string(200)  }
    weight:    {  type: integer      }
    height:    {  type: integer      }
    width:     {  type: integer      }
    lenght:    {  type: integer      }
    color:     {  type: string(45)   }
  relations:
    Havelist:
      local:   id
      foreign: id_object
      type:    one

Product:
  tableName: product
  actAs:
    Timestampable: ~
  columns:
    id:           {  type: integer,  primary: true,  autoincrement: true, notnull: true  }
    id_category:  {  type: integer  }
    name:         {  type: string(45)  }
    description:  {  type: string(150)  }
    picture:      {  type: string(200)  }
    link:         {  type: string(45)  }
    youtube:      {  type: string(100)  }
    brand:        {  type: string(45)  }
    model:        {  type: string(45)  }
  relations:
    Havelist:
      local:      id
      foreign:    product_id
      type:       many
    Category:
      class:      Category
      local:      id_category
      foreign:    id
      type:       one
      
Category:
  tableName: category
  columns:
    id:             {  type: integer, primary: true, autoincrement: true, notnull: true  }
    id_root:        {  type: integer  }
    name:           {  type: string(50)  }
  relations:
    Category:
      local:        id_root
      foreign:      id
      type:         one
    Products:
      class:        Product
      local:        id
      foreign:      id_category
      foreignAlias: Categories
      type:         many

Wantlist:
  tableName: want_list
  actAs:
    Timestampable: ~
  columns:
    id:                       {  type: integer,  primary: true,  autoincrement: true, notnull: true  }
    user_id:                  {  type: integer,  primary: true,  notnull: true  }
    product_id:              {  type: integer,  primary: true,  notnull: true  }
  relations:
    Product:
      class:        Product
      local:        product_id
      foreign:      id
      type:         one
      foreignType:  many
      foreignAlias: Wantlist
    User:
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      foreignAlias: Wantlist
      foreignType:  many
      type:         one
      onDelete:     CASCADE

Review:
  tableName: review
  actAs:
    Timestampable: ~
  columns:
    id:                       {  type: integer,  primary: true,  autoincrement: true, notnull: true  }
    user_id:                  {  type: integer,  primary: true,  notnull: true  }
    product_id:               {  type: integer,  primary: true,  notnull: true  }
    text:                     {  type: string(150)                              }
  relations:
    Product:
      class:        Product
      local:        product_id
      foreign:      id
      type:         one
      foreignType:  many
      foreignAlias: Review
      onDelete:     CASCADE
    User:
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      foreignAlias: Review
      foreignType:  many
      type:         one
      onDelete:     CASCADE

Rate:
  tableName: rate
  actAs:
    Timestampable: ~
  columns:
    intercambio_id:           {  type: integer,  primary: true,  notnull: true  }
    user_rated_id:            {  type: integer,  primary: true,  notnull: true  }
    user_rater_id:            {  type: integer,  primary: true,  notnull: true  }
    feedback:                 {  type: integer                  }
    text:                     {  type: string(150)              }
 
  relations:
    User_rated:
      class:        sfGuardUser
      local:        user_rated_id
      foreign:      id
      foreignAlias: Rated
      foreignType:  many
      type:         one
      onDelete:     CASCADE
    User_rater:
      class:        sfGuardUser
      local:        user_rater_id
      foreign:      id
      foreignAlias: Rates
      foreignType:  many
      type:         one
      onDelete:     CASCADE
  