#Lo siguiente es para cambiar el nombre a las tablas que genera el plugin
#sfGuardDoctrine el cual tenia nombres de tablas largos y poco semanticos
#INICIO CAMBIO NOMBRE TABLAS PLUGIN sfDoctrineGuard
sfGuardGroup:
  tableName: groups

sfGuardPermission:
  tableName: permissions

sfGuardGroupPermission:
  tableName: groups_permissions

sfGuardUser:
  tableName:  user_login

sfGuardUserPermission:
  tableName: user_permission

sfGuardUserGroup:
  tableName: user_group

sfGuardRememberKey:
  tableName: remember_key

sfGuardForgotPassword:
  tableName: forgot_password
#FIN CAMBIO NOMBRE TABLAS PLUGIN sfDoctrineGuard

#tabla de perfil de usuario:
sfGuardUserProfile:
  tableName: user_profile
  actAs:
    Timestampable: ~
  columns:
    user_id:        {  type: integer,  notnull: true  }
    first_name:     {  type: string(150)  }
    last_name:      {  type: string(150)  }
    address:        {  type: string(100)  }
    token:          {  type: string(32)   }
    facebook_uid:   {  type: string(20)   }
  relations:
    User:
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      foreignAlias: Profile
      foreignType:  one
      type:         one
      onDelete:     CASCADE

Havelist:
  tableName: havelist
  actAs:
    Timestampable: ~
  columns:
    id:             {  type: integer,  primary: true,  autoincrement: true, notnull: true  }
    id_product:     {  type: integer,  notnull: true                                       }
    id_object:      {  type: integer                                                       }
    user_id:        {  type: integer,  notnull: true                                       }
  relations:
    Product:
      local:        id_product
      foreign:      id
      type:         one
    Object:
      local:        id_object
      foreign:      id
      type:         one
    User:
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      foreignAlias: Havelist
      foreignType:  one
      type:         one
      onDelete:     CASCADE
      
Object:
  tableName: object
  actAs:
    Timestampable: ~
  columns:
    id:        {  type: integer,  primary: true,  autoincrement: true, notnull: true  }
    status:    {  type: string(45)   }
    detail:    {  type: string(150)  }
    picture:   {  type: string(200)  }
    weight:    {  type: integer      }
    height:    {  type: integer      }
    width:     {  type: integer      }
    lenght:    {  type: integer      }
    is_new:    {  type: boolean      }
    color:     {  type: string(45)   }
  relations:
    Havelist:
      local:   id
      foreign: id_object
      type:    one

Product:
  tableName: product
  actAs:
    Timestampable: ~
  columns:
    id:           {  type: integer,  primary: true,  autoincrement: true, notnull: true  }
    id_category:  {  type: integer  }
    name:         {  type: string(45)  }
    description:  {  type: string(150)  }
    picture:      {  type: string(200)  }
    link:         {  type: string(45)  }
    brand:        {  type: string(45)  }
    model:        {  type: string(45)  }
  relations:
    Havelist:
      local:      id
      foreign:    id_product
      type:       many
    Category:
      class:      Category
      local:      id_category
      foreign:    id
      type:       one
      
Category:
  tableName: category
  columns:
    id:             {  type: integer, primary: true, autoincrement: true, notnull: true  }
    id_root:        {  type: integer  }
    name:           {  type: string(50)  }
  relations:
    Category:
      local:        id_root
      foreign:      id
      type:         one
    Products:
      class:        Product
      local:        id
      foreign:      id_category
      foreignAlias: Categories
